arrowParens = "always"
bracketSpacing = true
insertPragma = false
jsxBracketSameLine = false
printWidth = 80
proseWrap = "always"
requirePragma = false
semi = true
singleQuote = false
tabWidth = 2
trailingComma = "all"

[[overrides]]
files = ["*.ts", "*.js"]
[overrides.options]
printWidth = 80

[[overrides]]
files = ["*.tsx", ".jsx"]
[overrides.options]
printWidth = 120

[[overrides]]
files = ["*.json", "*.json5"]
[overrides.options]
printWidth = 120

[[overrides]]
files = "*.md"
[overrides.options]
# proseWrap = "never"
